# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0004_auto_20171101_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='plants',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
