# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0005_auto_20171101_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='id',
        ),
        migrations.AlterField(
            model_name='plants',
            name='plant_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
