# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('values', '0006_auto_20171101_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
