# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0012_remove_plants_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='pid',
        ),
        migrations.DeleteModel(
            name='Plants',
        ),
    ]
