# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0013_auto_20171101_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='values.Plants'),
        ),
    ]
