# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0014_auto_20171101_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='plant_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
