# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0015_auto_20171104_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='plant_name',
            field=models.CharField(default='mango', max_length=1000),
        ),
    ]
