# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0016_plants_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='rain',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
